const DELTA_TIME = 0.05;

const GRAVITY_CONSTANT = 0.2;

const MASSPOINT_MASS = 1;
const MASSPOINT_RADIUS = 5;


const SPRING_SPRING_CONSTANT = 10;
const SPRING_DAMPING_CONSTANT = 40;

const SPRING_SHOW_STROKEWEIGHT = 2;

const SOFT_BODY_SIZE = 15;